"""init

Revision ID: bc825e97a933
Revises: 
Create Date: 2022-04-14 21:19:42.400799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc825e97a933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_description', table_name='clients')
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_index('ix_clients_poc_email', table_name='clients')
    op.drop_index('ix_clients_poc_name', table_name='clients')
    op.drop_index('ix_clients_poc_phone', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_tokens_expires', table_name='tokens')
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('ix_projects_description', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_index('ix_projects_project_status', table_name='projects')
    op.drop_index('ix_projects_start_time', table_name='projects')
    op.drop_index('ix_projects_stop_time', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_entries_entry_type', table_name='entries')
    op.drop_index('ix_entries_id', table_name='entries')
    op.drop_index('ix_entries_location', table_name='entries')
    op.drop_index('ix_entries_time', table_name='entries')
    op.drop_table('entries')
    op.drop_index('ix_grievances_description', table_name='grievances')
    op.drop_index('ix_grievances_grievance_type', table_name='grievances')
    op.drop_index('ix_grievances_image_url', table_name='grievances')
    op.drop_index('ix_grievances_name', table_name='grievances')
    op.drop_table('grievances')
    op.drop_index('ix_reports_description', table_name='reports')
    op.drop_index('ix_reports_id', table_name='reports')
    op.drop_index('ix_reports_start_time', table_name='reports')
    op.drop_index('ix_reports_stop_time', table_name='reports')
    op.drop_index('ix_reports_task_type', table_name='reports')
    op.drop_index('ix_reports_title', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('otp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('otp', name='users_otp_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_type', postgresql.ENUM('learning', 'project', 'others', name='taskenum'), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stop_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='reports_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    op.create_index('ix_reports_title', 'reports', ['title'], unique=False)
    op.create_index('ix_reports_task_type', 'reports', ['task_type'], unique=False)
    op.create_index('ix_reports_stop_time', 'reports', ['stop_time'], unique=False)
    op.create_index('ix_reports_start_time', 'reports', ['start_time'], unique=False)
    op.create_index('ix_reports_id', 'reports', ['id'], unique=False)
    op.create_index('ix_reports_description', 'reports', ['description'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grievance_type', postgresql.ENUM('harrassment', 'abuse', 'discriminitation', 'others', name='grievanceenum'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='grievances_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grievances_pkey')
    )
    op.create_index('ix_grievances_name', 'grievances', ['name'], unique=False)
    op.create_index('ix_grievances_image_url', 'grievances', ['image_url'], unique=False)
    op.create_index('ix_grievances_grievance_type', 'grievances', ['grievance_type'], unique=False)
    op.create_index('ix_grievances_description', 'grievances', ['description'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entry_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='entries_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entries_pkey')
    )
    op.create_index('ix_entries_time', 'entries', ['time'], unique=False)
    op.create_index('ix_entries_location', 'entries', ['location'], unique=False)
    op.create_index('ix_entries_id', 'entries', ['id'], unique=False)
    op.create_index('ix_entries_entry_type', 'entries', ['entry_type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stop_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('project_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['clients.id'], name='projects_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.create_index('ix_projects_stop_time', 'projects', ['stop_time'], unique=False)
    op.create_index('ix_projects_start_time', 'projects', ['start_time'], unique=False)
    op.create_index('ix_projects_project_status', 'projects', ['project_status'], unique=False)
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_description', 'projects', ['description'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=False)
    op.create_index('ix_tokens_expires', 'tokens', ['expires'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poc_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poc_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poc_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='clients_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clients_pkey')
    )
    op.create_index('ix_clients_poc_phone', 'clients', ['poc_phone'], unique=False)
    op.create_index('ix_clients_poc_name', 'clients', ['poc_name'], unique=False)
    op.create_index('ix_clients_poc_email', 'clients', ['poc_email'], unique=False)
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.create_index('ix_clients_description', 'clients', ['description'], unique=False)
    # ### end Alembic commands ###
